# docker-compose.yml

services:

  nginx:
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    ports:
      - 80:80
      - 443:443
    volumes:
      - certificates:/etc/letsencrypt
      - wordpress:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/user_conf.d/${DOMAIN}.conf:ro

  wordpress:
    image: wordpress:php8.3-fpm
    restart: always
    environment:
      - WORDPRESS_DB_HOST=${MYSQL_HOST}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD='1'
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always

volumes:
  certificates:
  wordpress:
  db:
