#SPDX-License-Identifier: MIT-0
---
# tasks file for setup

- name: Create app directory
  ansible.builtin.file:
    path: /cloud-1
    state: directory

- name: Upload docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /cloud-1

- name: Upload environment
  copy:
    src: .env
    dest: /cloud-1

- name: Include .env file
  ansible.builtin.include_vars:
    file: .env
    name: env_vars

- name: Generate configuration file
  template:
    src: nginx.conf.j2
    dest: /cloud-1/nginx.conf
  vars:
    domain: "{{ env_vars.DOMAIN }}"
    phpmyadmin_root: "/phpmyadmin"
    phpmyadmin_host: "phpmyadmin"
    wordpress_host: "wordpress"

- name: Pull containers
  community.docker.docker_compose_v2_pull:
    project_src: /cloud-1
